name: docker build push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Github 업스트림 체크아웃
        uses: actions/checkout@v2

      - name: JDK 11 설치
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: ./gradlew 권한 설정
        run: chmod +x gradlew

      - name: 빌드
        run: ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/Dockerfile
          push: true
          tags: dbfpzk142/concurrency:latest